### ISSUE TITLE
.gitignore file source

### ISSUE THREAD

**Issue by dimapasko** [skalinets/add-default-ignores#4]
Hi @skalinets 

I have question about your product vision.

I like this module but it would be even better if it takes `.gitignore` file from `https://github.com/github/gitignore` repo because it supported by the whole .NET community.

This changes was implemented in #2 by @Restuta but has been overwritten later at the commit 8ea29229bd90120a036dbed4714e008a7fa6d506

Is this was made by accident or you've made a strategic decision to use cached version from `/Content` folder only?

**Comment by skalinets** [comment]
@dimapasko . #2 has been made in times when `.gitignore`  did not have entries for ncrunch for example. However, it may be reasonable now to switch back to the community version :)

**Comment by dimapasko** [comment]
Cool, thx
